#!/usr/bin/env python3
"""Live ArUco surface visualization for ATMOS MoCap tracker development.

Phase 2.3 (step 1):
- Detect four configurable corner markers that define the table surface.
- Draw a live table outline (parallelogram in image space).
- Draw an XYZ world frame at the configured back-left corner.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import yaml


CORNER_KEYS = ["back_left", "back_right", "front_right", "front_left"]
ARUCO_DICT_OPTIONS = {
    "DICT_4X4_50": cv2.aruco.DICT_4X4_50,
    "DICT_4X4_100": cv2.aruco.DICT_4X4_100,
    "DICT_5X5_50": cv2.aruco.DICT_5X5_50,
    "DICT_6X6_50": cv2.aruco.DICT_6X6_50,
    "DICT_7X7_50": cv2.aruco.DICT_7X7_50,
}
WINDOW_NAME = "ATMOS MoCap Tracker - Surface Step"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Live table-surface visualization from four ArUco corner markers. "
            "The corner IDs are configurable so the table mapping can be changed "
            "without code edits."
        )
    )
    parser.add_argument(
        "--camera-index",
        type=int,
        default=0,
        help="Camera index for cv2.VideoCapture (default: 0).",
    )
    parser.add_argument(
        "--calibration-file",
        type=Path,
        default=None,
        help=(
            "Path to a calibration YAML generated by camera_calibration.py. "
            "If omitted, the newest file in fiducial_mocap/calibration is used."
        ),
    )
    parser.add_argument(
        "--aruco-dict",
        choices=sorted(ARUCO_DICT_OPTIONS.keys()),
        default="DICT_4X4_50",
        help="Aruco dictionary to use for marker detection.",
    )
    parser.add_argument(
        "--corner-ids",
        type=str,
        default="0,1,3,2",
        help=(
            "Comma-separated marker IDs in order: "
            "back_left,back_right,front_right,front_left. "
            "Example: 1,3,5,7"
        ),
    )
    parser.add_argument(
        "--table-side-m",
        type=float,
        default=1.0,
        help="Physical table side length in meters (default: 1.0).",
    )
    parser.add_argument(
        "--axis-length-m",
        type=float,
        default=0.20,
        help="XYZ axis length in meters for visualization (default: 0.20).",
    )
    parser.add_argument(
        "--robot-id",
        type=int,
        default=4,
        help="Marker ID used for the robot (default: 4).",
    )
    parser.add_argument(
        "--marker-length-m",
        type=float,
        default=0.15,
        help="Physical marker side length in meters for pose estimation (default: 0.15).",
    )
    parser.add_argument(
        "--origin-id",
        type=int,
        default=0,
        help="Marker ID used as world-frame origin for XYZ drawing (default: 0).",
    )
    parser.add_argument(
        "--undistort",
        dest="undistort",
        action="store_true",
        help="Enable undistortion before marker detection (default).",
    )
    parser.add_argument(
        "--no-undistort",
        dest="undistort",
        action="store_false",
        help="Disable undistortion and process raw camera frames.",
    )
    parser.set_defaults(undistort=True)
    return parser.parse_args()


def parse_corner_ids(corner_ids_raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in corner_ids_raw.split(",") if p.strip()]
    if len(parts) != 4:
        raise ValueError(
            "--corner-ids must provide exactly 4 IDs in order "
            "back_left,back_right,front_right,front_left."
        )

    ids = [int(p) for p in parts]
    if len(set(ids)) != 4:
        raise ValueError("--corner-ids must contain 4 unique IDs.")

    return {name: marker_id for name, marker_id in zip(CORNER_KEYS, ids)}


def find_latest_calibration_file(calibration_dir: Path) -> Path:
    if not calibration_dir.exists():
        raise FileNotFoundError(f"Calibration directory does not exist: {calibration_dir}")

    files = sorted(calibration_dir.glob("camera_calibration_*.yaml"))
    if not files:
        raise FileNotFoundError(
            f"No calibration files found in {calibration_dir}. "
            "Run camera_calibration.py first."
        )
    return files[-1]


def load_calibration(calibration_file: Path) -> Tuple[np.ndarray, np.ndarray, Optional[Tuple[int, int]]]:
    with calibration_file.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    camera_key = "camera_matrix" if "camera_matrix" in data else "K"
    distortion_key = "distortion_coefficients" if "distortion_coefficients" in data else "D"

    if camera_key not in data or distortion_key not in data:
        raise ValueError("Calibration YAML missing required keys.")

    camera_matrix = np.array(data[camera_key], dtype=np.float64)
    dist_coeffs = np.array(data[distortion_key], dtype=np.float64)

    calibration_dim: Optional[Tuple[int, int]] = None
    if "dim" in data and isinstance(data["dim"], list) and len(data["dim"]) == 2:
        calibration_dim = (int(data["dim"][0]), int(data["dim"][1]))
    elif "image_width" in data and "image_height" in data:
        calibration_dim = (int(data["image_width"]), int(data["image_height"]))

    # Fisheye model uses 4 coefficients. If calibration produced 5+, keep first 4.
    dist_coeffs = dist_coeffs.reshape(-1)
    if dist_coeffs.size >= 4:
        dist_coeffs = dist_coeffs[:4].reshape(4, 1)
    else:
        raise ValueError(
            "Calibration distortion coefficients are insufficient for fisheye undistortion. "
            "Need at least 4 values."
        )

    return camera_matrix, dist_coeffs, calibration_dim


def build_aruco_detector(dictionary_name: str) -> Tuple[cv2.aruco.Dictionary, cv2.aruco.DetectorParameters]:
    dictionary = cv2.aruco.getPredefinedDictionary(ARUCO_DICT_OPTIONS[dictionary_name])
    parameters = cv2.aruco.DetectorParameters()
    return dictionary, parameters


def marker_centers(
    corners: List[np.ndarray], ids: np.ndarray
) -> Dict[int, Tuple[float, float]]:
    id_to_center: Dict[int, Tuple[float, float]] = {}
    for idx, marker_id in enumerate(ids.flatten()):
        pts = corners[idx][0]
        center = np.mean(pts, axis=0)
        id_to_center[int(marker_id)] = (float(center[0]), float(center[1]))
    return id_to_center


def get_table_image_points(
    id_to_center: Dict[int, Tuple[float, float]],
    corner_id_map: Dict[str, int],
) -> Optional[np.ndarray]:
    points: List[Tuple[float, float]] = []
    for corner_name in CORNER_KEYS:
        marker_id = corner_id_map[corner_name]
        if marker_id not in id_to_center:
            return None
        points.append(id_to_center[marker_id])
    return np.array(points, dtype=np.float32)


def table_object_points(table_side_m: float) -> np.ndarray:
    return np.array(
        [
            [0.0, 0.0, 0.0],
            [table_side_m, 0.0, 0.0],
            [table_side_m, table_side_m, 0.0],
            [0.0, table_side_m, 0.0],
        ],
        dtype=np.float32,
    )


def draw_surface_overlay(frame: np.ndarray, image_points: np.ndarray) -> None:
    pts = image_points.astype(np.int32).reshape((-1, 1, 2))
    cv2.polylines(frame, [pts], isClosed=True, color=(255, 255, 0), thickness=3)

    labels = ["BL", "BR", "FR", "FL"]
    for idx, label in enumerate(labels):
        px, py = image_points[idx]
        cv2.circle(frame, (int(px), int(py)), 6, (0, 255, 255), -1)
        cv2.putText(
            frame,
            label,
            (int(px) + 8, int(py) - 8),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )


def draw_xyz_axes(
    frame: np.ndarray,
    rvec: np.ndarray,
    tvec: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    axis_length_m: float,
    forced_origin_px: Optional[Tuple[float, float]] = None,
) -> None:
    axes_points_3d = np.array(
        [
            [0.0, 0.0, 0.0],
            [axis_length_m, 0.0, 0.0],
            [0.0, axis_length_m, 0.0],
            [0.0, 0.0, -axis_length_m],
        ],
        dtype=np.float32,
    )

    projected, _ = cv2.projectPoints(
        axes_points_3d,
        rvec,
        tvec,
        camera_matrix,
        dist_coeffs,
    )
    p_float = projected.reshape(-1, 2)

    if forced_origin_px is not None:
        delta = np.array([forced_origin_px[0], forced_origin_px[1]], dtype=np.float32) - p_float[0]
        p_float = p_float + delta

    p = p_float.astype(np.int32)

    origin = tuple(p[0])
    px = tuple(p[1])
    py = tuple(p[2])
    pz = tuple(p[3])

    cv2.line(frame, origin, px, (0, 0, 255), 3)
    cv2.line(frame, origin, py, (0, 255, 0), 3)
    cv2.line(frame, origin, pz, (255, 0, 0), 3)

    cv2.putText(frame, "X", (px[0] + 6, px[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    cv2.putText(frame, "Y", (py[0] + 6, py[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
    cv2.putText(frame, "Z", (pz[0] + 6, pz[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2)


def compute_robot_planar_position(
    table_image_points: np.ndarray,
    table_side_m: float,
    robot_center_px: Tuple[float, float],
) -> Optional[np.ndarray]:
    table_xy = np.array(
        [
            [0.0, 0.0],
            [table_side_m, 0.0],
            [table_side_m, table_side_m],
            [0.0, table_side_m],
        ],
        dtype=np.float32,
    )

    homography, _ = cv2.findHomography(table_image_points, table_xy, method=0)
    if homography is None:
        return None

    pt = np.array([[[robot_center_px[0], robot_center_px[1]]]], dtype=np.float32)
    mapped = cv2.perspectiveTransform(pt, homography)
    return mapped.reshape(2)


def setup_fisheye_undistort_maps(
    undistort_dim: Tuple[int, int],
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    # Use DIM/K/D directly from calibration output (reference undistort flow).
    map1, map2 = cv2.fisheye.initUndistortRectifyMap(
        camera_matrix,
        dist_coeffs,
        np.eye(3),
        camera_matrix,
        undistort_dim,
        cv2.CV_16SC2,
    )
    return map1, map2, camera_matrix.copy()


def main() -> None:
    args = parse_args()
    corner_id_map = parse_corner_ids(args.corner_ids)

    calibration_file = args.calibration_file
    if calibration_file is None:
        calibration_file = find_latest_calibration_file(Path("fiducial_mocap/calibration"))

    camera_matrix, dist_coeffs, calibration_dim = load_calibration(calibration_file)
    aruco_dictionary, aruco_params = build_aruco_detector(args.aruco_dict)
    _ = table_object_points(args.table_side_m)

    cap = cv2.VideoCapture(args.camera_index)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open camera index {args.camera_index}.")

    print("Live tracker step 1: table surface visualization")
    print(f"Calibration: {calibration_file}")
    print("Corner ID map:")
    for key in CORNER_KEYS:
        print(f"  - {key}: {corner_id_map[key]}")
    print(f"Robot ID: {args.robot_id}")
    print(f"Origin ID: {args.origin_id}")
    print(f"Undistort (fisheye): {'ON' if args.undistort else 'OFF'}")
    print("Controls: q=quit")

    undistort_map1: Optional[np.ndarray] = None
    undistort_map2: Optional[np.ndarray] = None
    undistort_camera_matrix: Optional[np.ndarray] = None
    undistort_dim: Optional[Tuple[int, int]] = calibration_dim

    try:
        while True:
            ok, frame = cap.read()
            if not ok:
                continue

            active_frame = frame
            active_camera_matrix = camera_matrix
            active_dist_coeffs = dist_coeffs

            if args.undistort:
                if undistort_map1 is None or undistort_map2 is None or undistort_camera_matrix is None:
                    if undistort_dim is None:
                        undistort_dim = (frame.shape[1], frame.shape[0])
                    undistort_map1, undistort_map2, undistort_camera_matrix = setup_fisheye_undistort_maps(
                        undistort_dim,
                        camera_matrix,
                        dist_coeffs,
                    )

                remap_src = frame
                if undistort_dim is not None and (frame.shape[1], frame.shape[0]) != undistort_dim:
                    remap_src = cv2.resize(frame, undistort_dim, interpolation=cv2.INTER_LINEAR)

                active_frame = cv2.remap(
                    remap_src,
                    undistort_map1,
                    undistort_map2,
                    interpolation=cv2.INTER_LINEAR,
                    borderMode=cv2.BORDER_CONSTANT,
                )
                active_camera_matrix = undistort_camera_matrix
                active_dist_coeffs = np.zeros((4, 1), dtype=np.float64)

            gray = cv2.cvtColor(active_frame, cv2.COLOR_BGR2GRAY)
            corners, ids, _ = cv2.aruco.detectMarkers(
                gray,
                aruco_dictionary,
                parameters=aruco_params,
            )

            status_text = "Waiting for table markers"
            detected_count = 0
            robot_status_text = "Robot: not detected"

            if ids is not None and len(ids) > 0:
                cv2.aruco.drawDetectedMarkers(active_frame, corners, ids)

                marker_rvecs, marker_tvecs, _ = cv2.aruco.estimatePoseSingleMarkers(
                    corners,
                    args.marker_length_m,
                    active_camera_matrix,
                    active_dist_coeffs,
                )

                id_to_center = marker_centers(corners, ids)
                surface_image_points = get_table_image_points(id_to_center, corner_id_map)
                detected_count = sum(
                    1
                    for marker_id in corner_id_map.values()
                    if marker_id in id_to_center
                )

                if surface_image_points is not None:
                    draw_surface_overlay(active_frame, surface_image_points)

                    ids_flat = ids.flatten().tolist()

                    if args.origin_id in ids_flat:
                        status_text = f"Table + XYZ locked on ID{args.origin_id}"
                    else:
                        status_text = f"Table found, but origin ID{args.origin_id} not detected"

                    if args.robot_id in id_to_center:
                        robot_center = id_to_center[args.robot_id]
                        robot_xy = compute_robot_planar_position(
                            surface_image_points,
                            args.table_side_m,
                            robot_center,
                        )
                        cv2.circle(
                            active_frame,
                            (int(robot_center[0]), int(robot_center[1])),
                            8,
                            (0, 165, 255),
                            -1,
                        )
                        cv2.putText(
                            active_frame,
                            f"ID{args.robot_id}",
                            (int(robot_center[0]) + 8, int(robot_center[1]) + 22),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.6,
                            (0, 165, 255),
                            2,
                            cv2.LINE_AA,
                        )
                        if robot_xy is not None:
                            robot_status_text = (
                                f"Robot ID{args.robot_id}: x={robot_xy[0]:.3f} m, "
                                f"y={robot_xy[1]:.3f} m"
                            )
                        else:
                            robot_status_text = "Robot detected, homography solve failed"
                    else:
                        robot_status_text = f"Robot ID{args.robot_id}: not detected"
                else:
                    status_text = "Need all 4 corner markers for table outline"
                    if args.robot_id in id_to_center:
                        robot_status_text = (
                            f"Robot ID{args.robot_id} detected. "
                            "Show all 4 table markers to compute XY."
                        )

                ids_flat = ids.flatten().tolist()
                if args.origin_id in ids_flat:
                    origin_idx = ids_flat.index(args.origin_id)
                    origin_center = id_to_center[args.origin_id]
                    draw_xyz_axes(
                        active_frame,
                        marker_rvecs[origin_idx],
                        marker_tvecs[origin_idx],
                        active_camera_matrix,
                        active_dist_coeffs,
                        axis_length_m=args.axis_length_m,
                        forced_origin_px=origin_center,
                    )
                    cv2.circle(
                        active_frame,
                        (int(origin_center[0]), int(origin_center[1])),
                        8,
                        (0, 0, 255),
                        2,
                    )

            cv2.putText(
                active_frame,
                status_text,
                (16, 28),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.75,
                (255, 255, 255),
                2,
                cv2.LINE_AA,
            )
            cv2.putText(
                active_frame,
                f"Table markers detected: {detected_count}/4",
                (16, 56),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (255, 255, 255),
                2,
                cv2.LINE_AA,
            )
            cv2.putText(
                active_frame,
                robot_status_text,
                (16, 84),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (255, 255, 255),
                2,
                cv2.LINE_AA,
            )
            cv2.putText(
                active_frame,
                f"Undistort fisheye: {'ON' if args.undistort else 'OFF'}",
                (16, 112),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.65,
                (255, 255, 255),
                2,
                cv2.LINE_AA,
            )

            cv2.imshow(WINDOW_NAME, active_frame)
            key = cv2.waitKey(1) & 0xFF
            if key in (ord("q"), 27):
                break

            if cv2.getWindowProperty(WINDOW_NAME, cv2.WND_PROP_VISIBLE) < 1:
                break

    finally:
        if cap.isOpened():
            cap.release()
        try:
            cv2.destroyWindow(WINDOW_NAME)
        except cv2.error:
            pass
        cv2.destroyAllWindows()
        cv2.waitKey(1)


if __name__ == "__main__":
    main()
