#!/usr/bin/env python3
"""Live ArUco surface visualization for ATMOS MoCap tracker development.

Phase 2.3 (step 1):
- Detect four configurable corner markers that define the table surface.
- Draw a live table outline (parallelogram in image space).
- Draw an XYZ world frame at the configured back-left corner.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import yaml


CORNER_KEYS = ["back_left", "back_right", "front_right", "front_left"]
ARUCO_DICT_OPTIONS = {
    "DICT_4X4_50": cv2.aruco.DICT_4X4_50,
    "DICT_4X4_100": cv2.aruco.DICT_4X4_100,
    "DICT_5X5_50": cv2.aruco.DICT_5X5_50,
    "DICT_6X6_50": cv2.aruco.DICT_6X6_50,
    "DICT_7X7_50": cv2.aruco.DICT_7X7_50,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Live table-surface visualization from four ArUco corner markers. "
            "The corner IDs are configurable so the table mapping can be changed "
            "without code edits."
        )
    )
    parser.add_argument(
        "--camera-index",
        type=int,
        default=0,
        help="Camera index for cv2.VideoCapture (default: 0).",
    )
    parser.add_argument(
        "--calibration-file",
        type=Path,
        default=None,
        help=(
            "Path to a calibration YAML generated by camera_calibration.py. "
            "If omitted, the newest file in fiducial_mocap/calibration is used."
        ),
    )
    parser.add_argument(
        "--aruco-dict",
        choices=sorted(ARUCO_DICT_OPTIONS.keys()),
        default="DICT_4X4_50",
        help="Aruco dictionary to use for marker detection.",
    )
    parser.add_argument(
        "--corner-ids",
        type=str,
        default="0,1,3,2",
        help=(
            "Comma-separated marker IDs in order: "
            "back_left,back_right,front_right,front_left. "
            "Example: 1,3,5,7"
        ),
    )
    parser.add_argument(
        "--table-side-m",
        type=float,
        default=1.0,
        help="Physical table side length in meters (default: 1.0).",
    )
    parser.add_argument(
        "--axis-length-m",
        type=float,
        default=0.20,
        help="XYZ axis length in meters for visualization (default: 0.20).",
    )
    return parser.parse_args()


def parse_corner_ids(corner_ids_raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in corner_ids_raw.split(",") if p.strip()]
    if len(parts) != 4:
        raise ValueError(
            "--corner-ids must provide exactly 4 IDs in order "
            "back_left,back_right,front_right,front_left."
        )

    ids = [int(p) for p in parts]
    if len(set(ids)) != 4:
        raise ValueError("--corner-ids must contain 4 unique IDs.")

    return {name: marker_id for name, marker_id in zip(CORNER_KEYS, ids)}


def find_latest_calibration_file(calibration_dir: Path) -> Path:
    if not calibration_dir.exists():
        raise FileNotFoundError(f"Calibration directory does not exist: {calibration_dir}")

    files = sorted(calibration_dir.glob("camera_calibration_*.yaml"))
    if not files:
        raise FileNotFoundError(
            f"No calibration files found in {calibration_dir}. "
            "Run camera_calibration.py first."
        )
    return files[-1]


def load_calibration(calibration_file: Path) -> Tuple[np.ndarray, np.ndarray]:
    with calibration_file.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if "camera_matrix" not in data or "distortion_coefficients" not in data:
        raise ValueError("Calibration YAML missing required keys.")

    camera_matrix = np.array(data["camera_matrix"], dtype=np.float64)
    dist_coeffs = np.array(data["distortion_coefficients"], dtype=np.float64)
    return camera_matrix, dist_coeffs


def build_aruco_detector(dictionary_name: str) -> Tuple[cv2.aruco.Dictionary, cv2.aruco.DetectorParameters]:
    dictionary = cv2.aruco.getPredefinedDictionary(ARUCO_DICT_OPTIONS[dictionary_name])
    parameters = cv2.aruco.DetectorParameters()
    return dictionary, parameters


def marker_centers(
    corners: List[np.ndarray], ids: np.ndarray
) -> Dict[int, Tuple[float, float]]:
    id_to_center: Dict[int, Tuple[float, float]] = {}
    for idx, marker_id in enumerate(ids.flatten()):
        pts = corners[idx][0]
        center = np.mean(pts, axis=0)
        id_to_center[int(marker_id)] = (float(center[0]), float(center[1]))
    return id_to_center


def get_table_image_points(
    id_to_center: Dict[int, Tuple[float, float]],
    corner_id_map: Dict[str, int],
) -> Optional[np.ndarray]:
    points: List[Tuple[float, float]] = []
    for corner_name in CORNER_KEYS:
        marker_id = corner_id_map[corner_name]
        if marker_id not in id_to_center:
            return None
        points.append(id_to_center[marker_id])
    return np.array(points, dtype=np.float32)


def table_object_points(table_side_m: float) -> np.ndarray:
    return np.array(
        [
            [0.0, 0.0, 0.0],
            [table_side_m, 0.0, 0.0],
            [table_side_m, table_side_m, 0.0],
            [0.0, table_side_m, 0.0],
        ],
        dtype=np.float32,
    )


def draw_surface_overlay(frame: np.ndarray, image_points: np.ndarray) -> None:
    pts = image_points.astype(np.int32).reshape((-1, 1, 2))
    cv2.polylines(frame, [pts], isClosed=True, color=(255, 255, 0), thickness=3)

    labels = ["BL", "BR", "FR", "FL"]
    for idx, label in enumerate(labels):
        px, py = image_points[idx]
        cv2.circle(frame, (int(px), int(py)), 6, (0, 255, 255), -1)
        cv2.putText(
            frame,
            label,
            (int(px) + 8, int(py) - 8),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )


def draw_xyz_axes(
    frame: np.ndarray,
    rvec: np.ndarray,
    tvec: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    axis_length_m: float,
) -> None:
    axes_points_3d = np.array(
        [
            [0.0, 0.0, 0.0],
            [axis_length_m, 0.0, 0.0],
            [0.0, axis_length_m, 0.0],
            [0.0, 0.0, -axis_length_m],
        ],
        dtype=np.float32,
    )

    projected, _ = cv2.projectPoints(
        axes_points_3d,
        rvec,
        tvec,
        camera_matrix,
        dist_coeffs,
    )
    p = projected.reshape(-1, 2).astype(np.int32)

    origin = tuple(p[0])
    px = tuple(p[1])
    py = tuple(p[2])
    pz = tuple(p[3])

    cv2.line(frame, origin, px, (0, 0, 255), 3)
    cv2.line(frame, origin, py, (0, 255, 0), 3)
    cv2.line(frame, origin, pz, (255, 0, 0), 3)

    cv2.putText(frame, "X", (px[0] + 6, px[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    cv2.putText(frame, "Y", (py[0] + 6, py[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
    cv2.putText(frame, "Z", (pz[0] + 6, pz[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2)


def main() -> None:
    args = parse_args()
    corner_id_map = parse_corner_ids(args.corner_ids)

    calibration_file = args.calibration_file
    if calibration_file is None:
        calibration_file = find_latest_calibration_file(Path("fiducial_mocap/calibration"))

    camera_matrix, dist_coeffs = load_calibration(calibration_file)
    aruco_dictionary, aruco_params = build_aruco_detector(args.aruco_dict)
    table_points_3d = table_object_points(args.table_side_m)

    cap = cv2.VideoCapture(args.camera_index)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open camera index {args.camera_index}.")

    print("Live tracker step 1: table surface visualization")
    print(f"Calibration: {calibration_file}")
    print("Corner ID map:")
    for key in CORNER_KEYS:
        print(f"  - {key}: {corner_id_map[key]}")
    print("Controls: q=quit")

    try:
        while True:
            ok, frame = cap.read()
            if not ok:
                continue

            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            corners, ids, _ = cv2.aruco.detectMarkers(
                gray,
                aruco_dictionary,
                parameters=aruco_params,
            )

            status_text = "Waiting for table markers"
            detected_count = 0

            if ids is not None and len(ids) > 0:
                cv2.aruco.drawDetectedMarkers(frame, corners, ids)

                id_to_center = marker_centers(corners, ids)
                surface_image_points = get_table_image_points(id_to_center, corner_id_map)
                detected_count = sum(
                    1
                    for marker_id in corner_id_map.values()
                    if marker_id in id_to_center
                )

                if surface_image_points is not None:
                    draw_surface_overlay(frame, surface_image_points)

                    ok_pnp, rvec, tvec = cv2.solvePnP(
                        table_points_3d,
                        surface_image_points,
                        camera_matrix,
                        dist_coeffs,
                        flags=cv2.SOLVEPNP_ITERATIVE,
                    )
                    if ok_pnp:
                        draw_xyz_axes(
                            frame,
                            rvec,
                            tvec,
                            camera_matrix,
                            dist_coeffs,
                            axis_length_m=args.axis_length_m,
                        )
                        status_text = "Table surface + XYZ frame locked"
                    else:
                        status_text = "Table found, pose solve failed"
                else:
                    status_text = "Need all 4 corner markers for table outline"

            cv2.putText(
                frame,
                status_text,
                (16, 28),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.75,
                (255, 255, 255),
                2,
                cv2.LINE_AA,
            )
            cv2.putText(
                frame,
                f"Table markers detected: {detected_count}/4",
                (16, 56),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (255, 255, 255),
                2,
                cv2.LINE_AA,
            )

            cv2.imshow("ATMOS MoCap Tracker - Surface Step", frame)
            key = cv2.waitKey(1) & 0xFF
            if key == ord("q"):
                break

    finally:
        cap.release()
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
